steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast2-docker.pkg.dev/jeruk-sosmed/backend-jeruk-api/jeruk-sosmed-api:latest",
        ".",
      ]

  # Step 2: Push Docker image ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast2-docker.pkg.dev/jeruk-sosmed/backend-jeruk-api/jeruk-sosmed-api:latest",
      ]

  # Step 3: Deploy ke Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "jeruk-sosmed-api"
      - "--image"
      - "asia-southeast2-docker.pkg.dev/jeruk-sosmed/backend-jeruk-api/jeruk-sosmed-api:latest"
      - "--platform"
      - "managed"
      - "--region"
      - "asia-southeast2"
      - "--allow-unauthenticated"

timeout: 1200s # Waktu maksimal build (opsional)
